version: '3'

services:
  texlive:
    build: .
    image: texlive
  sut:
    image: blue271828/goss
    environment:
      GOSS_FILES_PATH: goss
      GOSS_FILES_STRATEGY: cp
    command: dgoss run -it texlive
    volumes:
      - ./goss:/goss/goss
      - /var/run/docker.sock:/var/run/docker.sock
